name: Pandoc Conversion

on: push

jobs:
    setup:
        runs-on: ubuntu-18.04
        outputs:
            matrix: ${{ steps.files_list.outputs.files }}
        steps:
            - uses: actions/checkout@v2
            - name: create file list
              id: files_list
              run: |
                cd reports
                echo "::set-output name=files::[$(printf '"%s", ' *.md)]"
    convert_to_pandoc:
        needs: [ setup ]
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                file: ${{fromJson(needs.setup.outputs.matrix)}}
        steps:
            - uses: actions/checkout@v2
            - name: Setup env vars
              run: |
                echo "OUTPUT=$(basename -s .md ${{matrix.file}})" >> $GITHUB_ENV
            - name: Create directory
              run: |
                mkdir artifacts
            - name: Convert mk to pdf
              uses: docker://pandoc/latex:2.17
              with:
                  args: >
                      reports/${{ matrix.file }}
                      --resource-path=reports/img/
                      -f markdown
                      -t pdf
                      -s
                      --output=artifacts/${{env.OUTPUT}}.pdf
            - name: Convert mk to html
              uses: docker://pandoc/latex:2.17
              with:
                  args: >
                      reports/${{ matrix.file }}
                      --resource-path=reports/img/
                      -f markdown
                      -t html
                      --mathml
                      -s
                      --output=artifacts/${{env.OUTPUT}}.html
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: artifacts_${{env.OUTPUT}}
                  path: artifacts
    build_zola:
        needs: [ convert_to_pandoc ]
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - name: Create directories
              run: |
                rm -R static/generated
                mkdir -p static/generated/pdfs/
                mkdir -p static/generated/html/
            - name: Download artifacts
              uses: actions/download-artifact@v2
              with:
                  path: artifacts/
            - name: Move artifacts
              run: |
                mv artifacts/**/*.html static/generated/html/
                mv static/artifacts/**/*.pdf static/generated/pdfs/
            - name: Build Zola and Deploy
              uses: shalzz/zola-deploy-action@v0.15.3
              env:
                # Target branch
                PAGES_BRANCH: gh-pages
                # Provide personal access token
                TOKEN: ${{ secrets.TOKEN }}
                    
                    